name = "sword-of-legends-mp"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[durable_objects.bindings]]
name = "MATCH"
class_name = "MatchRoom"

[[durable_objects.bindings]]
name = "PLAYERBOX"
class_name = "PlayerBox"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lobby", "MatchRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PlayerBox"]
